# Generated by Django 2.2.7 on 2019-11-26 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0002_substitute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='substitute_product',
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='usual_product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Substitute',
        ),
    ]
