# Generated by Django 2.2.7 on 2019-11-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_auto_20191127_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='substitute',
            name='usual_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usual_product', to='sub.Product'),
        ),
        migrations.RemoveField(
            model_name='substitute',
            name='substitute_product',
        ),
        migrations.AddField(
            model_name='substitute',
            name='substitute_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='substitute_product', to='sub.Product'),
        ),
    ]
