# Generated by Django 2.2.7 on 2019-12-01 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_auto_20191130_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
