# Generated by Django 2.2.7 on 2019-12-05 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0006_auto_20191201_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
    ]
