# Generated by Django 2.2.7 on 2019-12-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0007_auto_20191205_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.TextField(default='ups'),
        ),
    ]
